# -*- coding: utf-8 -*-
"""TallerOpti

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAiAUyagibGD-2_UhrZ0eWb7YjqW4Ysu
"""

import numpy as np
from scipy.optimize import minimize, linprog

# ============================================================
# PROBLEMA 1: MEZCLA DE FERTILIZANTES
# ============================================================

print('=' * 55)
print('  PROBLEMA 1: MEZCLA DE FERTILIZANTES')
print('=' * 55)

# a) Variables de decisión
print("\na) Variables de decisión:")
print("   x1 = toneladas producidas de Fertilizante F1")
print("   x2 = toneladas producidas de Fertilizante F2")

# b) Función objetivo
print("\nb) Función objetivo (maximizar ganancia):")
print("   max Z = 0.18*x1 + 0.22*x2")

# c) Restricciones
print("\nc) Restricciones:")
print("   Compuesto A : 3*x1 + 4*x2 <= 120")
print("   Compuesto B : 2*x1 + 1*x2 <= 80")
print("   Compuesto C : 5*x1 + 3*x2 <= 150")
print("   No negatividad: x1 >= 0, x2 >= 0")

# d) Clasificación
print("\nd) Clasificación del modelo:")
print("   - LINEAL: función objetivo y restricciones son")
print("     combinaciones lineales de x1 y x2 (sin productos")
print("     ni potencias entre variables).")
print("   - CONTINUO: x1 y x2 pueden tomar cualquier valor")
print("     real no negativo (toneladas fraccionarias posibles).")

# Resolución con linprog (minimiza, por eso negamos coeficientes)
c_obj = [-180, -220]   # negado para maximizar
A_ub  = [[3, 4],
          [2, 1],
          [5, 3]]
b_ub  = [120, 80, 150]
bounds = [(0, None), (0, None)]

res = linprog(c_obj, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

x1_opt, x2_opt = res.x
ganancia_opt   = -res.fun

print()
print('-' * 55)
print('  Solución óptima (referencia):')
print('-' * 55)
print(f"  F1 (x1) = {x1_opt:.4f} toneladas")
print(f"  F2 (x2) = {x2_opt:.4f} toneladas")
print(f"  Ganancia máxima = ${ganancia_opt:.2f}")
print(f"  Uso compuesto A : {3*x1_opt + 4*x2_opt:.1f} / 120 kg")
print(f"  Uso compuesto B : {2*x1_opt + 1*x2_opt:.1f} / 80  kg")
print(f"  Uso compuesto C : {5*x1_opt + 3*x2_opt:.1f} / 150 kg")
print('=' * 55)

# ============================================================
# PROBLEMA 2: PRODUCCIÓN SEMANAL DE UNA FÁBRICA
# ============================================================

print()
print('=' * 55)
print('  PROBLEMA 2: PRODUCCIÓN SEMANAL DE UNA FÁBRICA')
print('=' * 55)

# a) Variables
print("\na) Variables:")
print("   Dependientes  : S_n (sillas semana n), M_n (mesas semana n)")
print("   Independiente : n (número de semana, discreta)")

# b) Clasificación
print("\nb) Clasificación:")
print("   - LINEAL   : S_{n+1} y M_{n+1} son combinaciones")
print("     lineales de S_n y M_n (sin términos cuadráticos")
print("     ni productos entre variables).")
print("   - DISCRETO : n toma valores enteros 0,1,2,...")

# c) Cálculo semanas 1 y 2
S0, M0 = 200, 80

def siguiente_semana(S, M):
    S_next = 0.6*S + 0.2*M + 40
    M_next = 0.1*S + 0.5*M + 20
    return S_next, M_next

S1, M1 = siguiente_semana(S0, M0)
S2, M2 = siguiente_semana(S1, M1)

print("\nc) Cálculo de semanas 1 y 2:")
print(f"\n   Semana 0: S0 = {S0},  M0 = {M0}")
print(f"\n   Semana 1:")
print(f"   S1 = 0.6({S0}) + 0.2({M0}) + 40 = {0.6*S0} + {0.2*M0} + 40 = {S1:.1f}")
print(f"   M1 = 0.1({S0}) + 0.5({M0}) + 20 = {0.1*S0} + {0.5*M0} + 20 = {M1:.1f}")
print(f"\n   Semana 2:")
print(f"   S2 = 0.6({S1:.1f}) + 0.2({M1:.1f}) + 40 = {S2:.2f}")
print(f"   M2 = 0.1({S1:.1f}) + 0.5({M1:.1f}) + 20 = {M2:.2f}")

# d) Sistema de equilibrio
print("\nd) Sistema de equilibrio (S* y M*):")
print("   Igualando S_{n+1}=S* y M_{n+1}=M*:")
print()
print("   0.4·S* - 0.2·M* = 40")
print("  -0.1·S* + 0.5·M* = 20")

A_eq = np.array([[0.4, -0.2],
                  [-0.1, 0.5]])
b_eq = np.array([40, 20])
equilibrio = np.linalg.solve(A_eq, b_eq)

print()
print('-' * 55)
print('  Valores de equilibrio:')
print('-' * 55)
print(f"  S* = {equilibrio[0]:.2f} sillas")
print(f"  M* = {equilibrio[1]:.2f} mesas")

# Simulación convergencia
semanas = 30
S_hist = [S0]; M_hist = [M0]
S, M = S0, M0
for _ in range(semanas):
    S, M = siguiente_semana(S, M)
    S_hist.append(S); M_hist.append(M)

print(f"\n  Verificación (semana {semanas}): S={S_hist[-1]:.2f}, M={M_hist[-1]:.2f}")
print('=' * 55)

# ============================================================
# PROBLEMA 3: EPIDEMIA EN UNA CIUDAD (MODELO SIS)
# ============================================================

print()
print('=' * 55)
print('  PROBLEMA 3: EPIDEMIA EN UNA CIUDAD (SIS)')
print('=' * 55)

beta  = 0.00003
gamma = 0.1
N     = 10000
I0    = 50

# a) Variables y parámetros
print("\na) Variables y parámetros:")
print("   Variable dependiente  : I(t) — infectados en tiempo t")
print("   Variable independiente: t — tiempo en días")
print(f"   β  = {beta}  (tasa de contagio por día)")
print(f"   γ  = {gamma}    (tasa de recuperación por día)")
print(f"   N  = {N}  (población total constante)")

# b) No linealidad
print("\nb) No linealidad:")
print("   El término β·(N-I)·I contiene I² al expandirse:")
print("   β·N·I - β·I²  → el término I² hace el modelo NO LINEAL.")

# c) Condición inicial
print(f"\nc) Condición inicial:  I(0) = {I0} personas infectadas")

# d) Puntos de equilibrio
print("\nd) Puntos de equilibrio  (dI/dt = 0):")
print("   β·(N-I*)·I* - γ·I* = 0")
print("   I*·[ β·(N-I*) - γ ] = 0")
print()

I_eq1 = 0
# β(N - I*) = γ  →  I* = N - γ/β
I_eq2 = N - gamma / beta

print(f"   Equilibrio 1: I* = {I_eq1}")
print(f"   Equilibrio 2: I* = N - γ/β = {N} - {gamma}/{beta} = {I_eq2:.2f}")

# e) Interpretación
print("\ne) Interpretación física:")
print(f"   I* = 0       → Libre de enfermedad (extinción). Inestable")
print(f"                  si β·N > γ (R0 = β·N/γ = {beta*N/gamma:.1f} > 1).")
print(f"   I* ≈ {I_eq2:.0f}  → Endémico estable. Contagios = recuperaciones.")
print(f"                  Con I(0)=50, la epidemia converge a ~{I_eq2:.0f}.")

# Simulación numérica con Euler
dt = 0.1
t_max = 200
t_vals = np.arange(0, t_max, dt)
I_vals = [I0]
I_curr = I0
for _ in t_vals[1:]:
    dI = beta*(N - I_curr)*I_curr - gamma*I_curr
    I_curr = I_curr + dI*dt
    I_vals.append(I_curr)

print()
print('-' * 55)
print('  Verificación numérica (Euler):')
print('-' * 55)
print(f"  I(t=50)  = {I_vals[int(50/dt)]:.1f}")
print(f"  I(t=100) = {I_vals[int(100/dt)]:.1f}")
print(f"  I(t=200) = {I_vals[-1]:.1f}  (equilibrio ≈ {I_eq2:.1f})")
print('=' * 55)

# ============================================================
# PROBLEMA 4: MODELO LOGÍSTICO DE PESCA
# ============================================================

print()
print('=' * 55)
print('  PROBLEMA 4: MODELO LOGÍSTICO DE PESCA')
print('=' * 55)

r_fish = 0.4
K      = 1000
H      = 80
P0     = 400

# a) Variables y parámetros
print("\na) Variables y parámetros:")
print("   Variable dependiente  : P_n — población al final del año n")
print("   Variable independiente: n   — año (discreto, entero)")
print(f"   r = {r_fish}  (tasa de crecimiento intrínseca)")
print(f"   K = {K}  (capacidad máxima de la laguna, peces)")
print(f"   H = {H}    (peces extraídos por año)")

# b) No linealidad y discreto
print("\nb) No lineal y discreto:")
print("   No lineal : el término r·P_n·(1 - P_n/K) contiene P_n².")
print("   Discreto  : n toma valores enteros (año 1, 2, 3, ...).")

# c) P1 y P2
def siguiente_año(P):
    return P + r_fish*P*(1 - P/K) - H

P1 = siguiente_año(P0)
P2 = siguiente_año(P1)

print(f"\nc) Cálculo de P1 y P2:")
print(f"\n   P0 = {P0}")
print(f"   P1 = {P0} + 0.4·{P0}·(1 - {P0}/{K}) - {H}")
print(f"      = {P0} + {r_fish*P0:.1f}·{1 - P0/K:.1f} - {H} = {P1:.2f}")
print(f"\n   P2 = {P1:.2f} + 0.4·{P1:.2f}·(1 - {P1:.2f}/{K}) - {H}")
print(f"      = {P2:.4f}")

# d) Puntos de equilibrio
print("\nd) Puntos de equilibrio  (P_{n+1} = P_n = P*):")
print("   r·P*·(1 - P*/K) - H = 0")
print("   0.4·P*·(1 - P*/1000) = 80")
print("   P*² - 1000·P* + 200000 = 0")

a_coef = 1
b_coef = -1000
c_coef = 200000
discriminante = b_coef**2 - 4*a_coef*c_coef
P_eq1 = (-b_coef + np.sqrt(discriminante)) / (2*a_coef)
P_eq2 = (-b_coef - np.sqrt(discriminante)) / (2*a_coef)

print(f"\n   Discriminante = {discriminante}")
print(f"   P*₁ = (1000 + √{discriminante}) / 2 = {P_eq1:.2f} peces  (estable)")
print(f"   P*₂ = (1000 - √{discriminante}) / 2 = {P_eq2:.2f} peces  (inestable)")

# e) Interpretación
print("\ne) Interpretación física:")
print(f"   P*₁ ≈ {P_eq1:.0f} peces → Equilibrio ESTABLE.")
print(f"          La reproducción y la pesca se compensan.")
print(f"          Con P0={P0} > {P_eq2:.0f}, la población converge aquí.")
print(f"\n   P*₂ ≈ {P_eq2:.0f} peces → Equilibrio INESTABLE (umbral crítico).")
print(f"          Si P0 < {P_eq2:.0f}: reproducción < cosecha → extinción.")
print(f"          Si P0 > {P_eq2:.0f}: población converge a ~{P_eq1:.0f}.")

# Simulación para verificar
años = 40
P_sobre = [P0]
P_bajo  = [250]   # por debajo del umbral
P_s, P_b = P0, 250
for _ in range(años):
    P_s = max(siguiente_año(P_s), 0)
    P_b = max(siguiente_año(P_b), 0)
    P_sobre.append(P_s)
    P_bajo.append(P_b)

print()
print('-' * 55)
print('  Verificación simulación (40 años):')
print('-' * 55)
print(f"  P0=400 (sobre umbral) → año 40: {P_sobre[-1]:.1f} peces")
print(f"  P0=250 (bajo umbral)  → año 40: {P_bajo[-1]:.1f} peces (extinción)")
print('=' * 55)